const awsconfig = {
	AWS_REGION: process.env.NEXT_PUBLIC_AWS_REGION,
	AWS_COGNITO_IDENTITY_POOL_ID: process.env.NEXT_PUBLIC_AWS_COGNITO_IDENTITY_POOL_ID,
	AWS_COGNITO_USER_POOL_ID: process.env.NEXT_PUBLIC_AWS_COGNITO_USER_POOL_ID,
	AWS_COGNITO_CLIENT_ID: process.env.NEXT_PUBLIC_AWS_COGNITO_CLIENT_ID,
	AWS_COGNITO_CLIENT_DOMAIN_NAME: process.env.NEXT_PUBLIC_AWS_COGNITO_CLIENT_DOMAIN_NAME,
	AWS_COGNITO_IDP_NAME: process.env.NEXT_PUBLIC_AWS_COGNITO_IDP_NAME,
	AWS_COGNITO_IDP_SIGNIN_URL: process.env.NEXT_PUBLIC_AWS_COGNITO_IDP_SIGNIN_URL,
	AWS_COGNITO_IDP_SIGNOUT_URL: process.env.NEXT_PUBLIC_AWS_COGNITO_IDP_SIGNOUT_URL,
	AWS_COGNITO_IDP_OAUTH_CLAIMS: process.env.NEXT_PUBLIC_AWS_COGNITO_IDP_OAUTH_CLAIMS.split(' '),
	AWS_COGNITO_IDP_GRANT_FLOW: process.env.NEXT_PUBLIC_AWS_COGNITO_IDP_GRANT_FLOW,
};

export default awsconfig;
