#Determines name of pipeline run. Default name is like 'master+99999' if the run id is 99999 and the source branch
#Can be overwritten in pipeline if needed
name: $(Build.SourceBranchName)+$(BuildID)

#Determines when pipeline runs automatically.
#Can be branches, tags, folders
#Full syntax required for anything except branches
trigger:
  # - master
  # - main
  # - dev
  - develop
  # - feature/*
  # - bundle/*
  # - release/*

#Reference to the repositories that contains all YAML files for this pattern
resources:
  repositories:
    - repository: TemplateRepo
      type: git
      name: shared-it-iac-pipeline-templates
      ref: refs/tags/0.0.50
    - repository: DevSecOpsYAML
      type: git
      name: shared-it-devsecops-yaml
      ref: refs/heads/release/2023-07-03

#References variables file located within repository that is native to the pipeline
#Can be changed to any location with repositroy
#Requires '@self' to ensure it targets triggering repository
#Case sensitive
variables:
  - template: ${{ parameters.VariableLocation }}/pipeline.yml

#Agent pool is set in the pipeline level variables file.
pool:
  name: $(agentPool)

parameters:
  #The cloud provider(s) to upload pipeline artifacts to for terraform deployment
  - name: DestinationCloud
    default: "AWS"
    displayName: "Destination Cloud Provider(s)"
    type: string
    values:
      - AWS
      - Azure
      - GCP

  #Below Parameter to enable Terraform container.
  #- name: IncludeContainer
  #  default: false
  #  displayName: "Enable Terraform Container"
  #  type: boolean

  # Pattern specific parameter
  # Edit parameter values as needed, do not change parameter names
  # bucketSuffix, sourceFolder, awsRegionAbbreviation, and globExpressions can be pipeline variables.
  # targetFolder, awsRegionCode must be specified here as parameters for each s3 upload as they are used in task display name.
  # for upload to root of bucket, leave targetFolder empty.
  # if multiple buckets, bucketSuffix must be unique pipeline variable per bucket or specified as parameters here.
  # if multiple uploads, sourceFolder, targetFolder, globExpressions must be unique pipeline variable per upload or specified as parameters here.
  # if multiple regions, awsRegionAbbreviation must be unique pipeline variable per region or specified as parameters here.
  # Add more entries to a parameter to add additional steps, second entry left commented as example.
  - name: "S3Info"
    displayName: "S3 Upload Information"
    type: object
    default:
      - bucketSuffix: $(bucketSuffix)
        sourceFolder: $(sourceFolder)
        targetFolder: pipeline-artifact
        globExpressions: $(globExpressions)
        awsRegionCode: $(awsRegionCode)
        awsRegionAbbreviation: $(awsRegionAbbreviation)
    #- bucketSuffix: $(bucketSuffix2)
    #  sourceFolder: $(sourceFolder2)
    #  targetFolder:
    #  globExpressions: $(globExpressions2)
    #  awsRegionCode: us-east-1
    #  awsRegionAbbreviation: $(awsRegionAbbreviation2)
  # - name: "AzureInfo"
  #   displayName: "Azure Upload Information"
  #   type: object
  #   default:
  #     - sourceFolder: ""
  #       containerName: ""
  #       blobPrefix: ""
  #       additionalArgumentsForBlobCopy: ""
  #       cleanTargetBeforeCopy: false
  #       azRegionCode: ""

  # #Below is Container Info Object for Terraform Container deployment
  # - name: "ContainerInfo"
  #   displayName: "Terraform Container Info"
  #   type: object
  #   default:
  #     - sourceDirectory: ""
  #       name: ""
  #       tag: ""
  #       dockerFile: ""
  #       build: true

  #Timeout in minutes for all jobs in this run, default is 60 minutes.
  #DevSecOps gets alerts for jobs that run longer than 120 minutes.
  #No action is taken against long running jobs, but we may ask why its taking so long if it consistently occurrs
  - name: TimeoutInMinutes
    default: 60
    displayName: "Job Timeout in Minutes"
    type: string

  #List of environments for application
  #Uncomment environments as needed
  - name: "Environments"
    displayName: Environments
    type: object
    default:
      - env: dev
      #- env: tst
      #- env: qa
      #- env: prd

  #Base portion of service connection name, generally pipeline name
  - name: SCName
    default: sdge-it-nla
    displayName: "AWS Service Connection Prefix"
    type: string

  #Location of pipeline variable files within triggering repository
  #Case sensitive
  #file names must be 'build.yml', 'dev.yml', 'tst.yml', 'qa.yml', 'prd.yml',
  #If located within Variables folder at root of repo, value is 'Variables'
  #Do not add a trailing slash
  - name: VariableLocation
    default: Variables
    displayName: "Path to Pipeline Variables"
    type: string

  #Parameters to force deployment of Dev, TST, and QA stages
  #These override branch restrictions for deployment stages
  #CanaryMode overrides these and only Dev option will work in CanaryMode
  - name: MakeDevGo
    default: false
    displayName: "Force Deploy Dev"
    type: boolean
  - name: MakeTstGo
    default: false
    displayName: "Force Deploy TST"
    type: boolean
  - name: MakeQAGo
    default: false
    displayName: "Force Deploy QA"
    type: boolean

  #Terraform Parameters
  #Enables extra steps that are required when running against terraform cloud
  - name: TerraformCloud
    default: true
    displayName: "Enable Terraform Cloud"
    type: boolean

  #Enables debug output from all terraform tasks except checkov
  - name: TerraformDebug
    default: false
    displayName: "Terraform Debug"
    type: boolean

  #This must remain as 'ChangeMeIfNeeded' in the YAML. CI/triggered runs for tf state remove are not supported.
  #Change this on the pipeline queue when needing to use tf state remove.
  - name: terraformStateResourceToRemove
    default: "ChangeMeIfNeeded"
    displayName: Terraform State Resource To Remove
    type: string

  - name: terraformDestroy
    displayName: Terraform Destroy
    default: false
    type: boolean

  #Enable canary mode
  #Pushes pipeline to Dev agent pool to allow for agent dependency upgrade testing and validation.
  #Limits pipeline to Build and Dev stages.
  - name: CanaryMode
    default: false
    displayName: "Canary Mode"
    type: boolean

  #Enable logic to source application build job(s) from triggering repository
  - name: LocalBuildYAML
    default: true
    displayName: "Use Build Job YAML From Local Repo"
    type: boolean

  #Enable logic to source pre S3 upload infra steps from triggering repository if needed
  - name: LocalPreTFYAML
    type: boolean
    default: false

  #Enable logic to source post tf-apply release steps from triggering repository if needed
  - name: LocalReleaseYAML
    default: true
    displayName: "Use Release Step YAML From Local Repo"
    type: boolean

  #Checkmarx parameters

  #Toggle between on-prem checkmarx and cloud-based CheckmarxOne functionality
  - name: UseNewCheckmarx
    default: true
    displayName: "Use CheckmarxOne instead of Checkmarx"
    type: boolean

  #Service Now parameters

  #Enable Service Now Functionality
  - name: EnableSNOW
    default: true
    displayName: "Enable Service Now Functionality"
    type: boolean

  #Edit to ServiceNow assignment group assigned to application/team
  - name: AssignmentGroup
    default: "CM-TOA:APPL GENERAL"
    displayName: "Assignment Group Name"
    type: string

  #Edit to ServiceNow CI-Name group assigned to application/team
  - name: CIName
    default: "APM0002920"
    displayName: "CI Name"
    type: string

  #Select option at pipeline runtime
  #Set default option for CI based runs
  #Do not change list of values. ServiceNow will reject any values not in this list.
  - name: ChangeReason
    default: "Maintenance"
    displayName: "Change Reason"
    type: string
    values:
      - Small Enhancement
      - Maintenance
      - Warranty Fix
      - Bug Fix
      - Business Continuity

  #Select option at pipeline runtime
  #Set default option for CI based runs
  #Do not change list of values. ServiceNow will reject any values not in this list.
  - name: ChangeWindow
    default: "Business Hours"
    displayName: "Change Window"
    type: string
    values:
      - Weekend Maintenance Window
      - Off Business Hours
      - Business Hours

  #Enter reason at pipeline runtime
  #Set default option for CI based runs
  #Required when ChangeWindow is `Business Hours`
  - name: BusinessHourJustification
    default: "Support is available"
    displayName: "Business Hour Justification"
    type: string

  #Enter reason at pipeline runtime
  #Set default option for CI based runs
  #Required for all production runs
  - name: ReleaseComments
    default: "Change when queueing build"
    displayName: "Release Comments"
    type: string

#Reference to remote pipeline template in shared-it-devsecops-yaml repo
extends:
  template: Pipeline-Templates/Terraform-Only/Pipeline/Pipeline.yml@DevSecOpsYAML
  parameters:
    DestinationCloud: ${{ parameters.DestinationCloud }}
    # IncludeContainer: ${{ parameters.IncludeContainer }}
    # ContainerInfo: ${{ parameters.ContainerInfo }}
    S3Info: ${{ parameters.S3Info }}
    # AzureInfo: ${{ parameters.AzureInfo }}
    Environments: ${{ parameters.Environments }}
    TimeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
    SCName: ${{ parameters.SCName }}
    VariableLocation: ${{ parameters.VariableLocation }}
    MakeDevGo: ${{ parameters.MakeDevGo }}
    MakeTSTGo: ${{ parameters.MakeTSTGo }}
    MakeQAGo: ${{ parameters.MakeQAGo }}
    TerraformCloud: ${{ parameters.TerraformCloud }}
    TerraformDebug: ${{ parameters.TerraformDebug }}
    TerraformDestroy: ${{ parameters.TerraformDestroy }}
    terraformStateResourceToRemove: ${{ parameters.terraformStateResourceToRemove }}
    CanaryMode: ${{ parameters.CanaryMode }}
    LocalBuildYAML: ${{ parameters.LocalBuildYAML }}
    LocalPreTFYAML: ${{ parameters.LocalPreTFYAML }}
    LocalReleaseYAML: ${{ parameters.LocalReleaseYAML }}
    UseNewCheckmarx: true
    EnableSNOW: ${{ parameters.EnableSNOW }}
    AssignmentGroup: ${{ parameters.AssignmentGroup }}
    ChangeWindow: ${{ parameters.ChangeWindow }}
    BusinessHourJustification: ${{ parameters.BusinessHourJustification }}
    ChangeReason: ${{ parameters.ChangeReason }}
    ReleaseComments: ${{ parameters.ReleaseComments }}
    CIName: ${{ parameters.CIName }}
