variable "region" {
  type        = string
  description = "The AWS region where to deploy Terraform resources"
}

variable "environment" {
  type = string
}

variable "application_use" {
  type        = string
  description = "The application use for Terraform resources"
}

variable "namespace" {
  type        = string
  description = "The AWS namespace to deploy Terraform resources"
}

variable "company_code" {
  type        = string
  description = "The company code prefix for Terraform resources"
}

variable "unit" {
  type        = string
  description = "Organizational unit"
}

variable "application_code" {
  type        = string
  description = "The application code prefix for Terraform resources"
}

variable "environment_code" {
  type        = string
  description = "The environment code prefix for Terraform resources"
}

variable "region_code" {
  type        = string
  description = "The AWS region short code prefix where to deploy Terraform resources"
}

variable "owner" {
  type        = string
  description = "The AWS Terraform resources owner"
}

variable "tag-version" {
  type        = string
  description = "Holds the version of the tagging format."
}

variable "billing-guid" {
  type        = string
  description = "Internal order - from SAP"
}

variable "portfolio" {
  type        = string
  description = "Portfolio associated with the application"
}

variable "support-group" {
  type        = string
  description = "Distribution list in email format"
}

variable "cmdb-ci-id" {
  type        = string
  description = "CI ID as generated by ServiceNow CMDB"
}

variable "data-classification" {
  type        = string
  description = "Data privacy classification"
}
variable "transcribe_lambda_role_arn" {
  type = string
}

variable "comprehend_lambda_role_arn" {
  type = string
}

variable "informational_macie_lambda_role_arn" {
  type = string
}

variable "macie_lambda_role_arn" {
  type = string
}

variable "trigger_macie_lambda_role_arn" {
  type = string
}

variable "nla_replication_role_arn" {
  type        = string
  description = "S3 replication role"
}

# variable "account_id_insights" {
#   type        = string
#   description = "AWS Account ID for NLA Insights"
# }

# variable "aws_assume_role_insights" {
#   type        = string
#   description = "aws_assume_role_insights"
# }
