
# requires transcribe iam role access
module "ccc_transcribe_lambda" {
  source  = "app.terraform.io/SempraUtilities/seu-lambda/aws"
  version = "6.0.0-prerelease"


  company_code     = "ent"
  application_code = "nla"
  environment_code = "sbx"
  region_code      = "wus2"
  application_use  = "lambda"
  description   = "Transcribe Call lambda function"
  handler       = "run.lambda_handler"
  runtime       = "python3.8"

  source_path = "${path.module}/../../backend/python/src/ccc_transcribe_lambda/lambda_handler.py"
  lambda_role = module.transcribe_lambda_role.name
  environment_variables = {
    AWS_ENVIRONMENT                 = var.environment
  }
  tags = {
    name                = "ccc-transcribe-lambda-${var.environment}"
    tag-version         = ""
    billing-guid        = "Internal order - from SAP"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
    portfolio           = "Portfolio"
    unit                = "Unit"
  }
}

resource "aws_lambda_permission" "unrefined_data_trigger" {
  statement_id  = "AllowExecutionFromS3Bucket"
  action        = "lambda:InvokeFunction"
  function_name = "ccc-transcribe-lambda"
  principal     = "s3.amazonaws.com"
  source_arn    = var.ccc_unrefined_call_data_bucket-arn
} 

# requires aws comprehend, s3 iam access
module "ccc_comprehend_lambda" {
  source  = "app.terraform.io/SempraUtilities/seu-lambda/aws"
  version = "6.0.0-prerelease"

  company_code     = "ent"
  application_code = "nla"
  environment_code = "sbx"
  region_code      = "wus2"
  application_use  = "lambda"
  description   = "Comprehend data lambda function"
  handler       = "run.lambda_handler"
  runtime       = "python3.8"

  source_path = "${path.module}/../../backend/python/src/ccc_comprehend_lambda/lambda_handler.py"
  lambda_role = module.comprehend_lambda_role.name
  environment_variables = {
    AWS_ENVIRONMENT                 = var.environment
  }
  tags = {
    name                = "ccc-comprehend-lambda-${var.environment}"
    tag-version         = ""
    billing-guid        = "Internal order - from SAP"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
    portfolio           = "Portfolio"
    unit                = "Unit"
  }
}
resource "aws_lambda_permission" "transcribed_data_trigger" {
  statement_id  = "AllowExecutionFromS3Bucket"
  action        = "lambda:InvokeFunction"
  function_name = "ccc-comprehend-lambda"
  principal     = "s3.amazonaws.com"
  source_arn    = var.ccc_verified_clean_bucket-arn
} 

module "informational_macie_lambda" {
  source  = "app.terraform.io/SempraUtilities/seu-lambda/aws"
  version = "6.0.0-prerelease"

  company_code     = "ent"
  application_code = "nla"
  environment_code = "sbx"
  region_code      = "wus2"
  application_use  = "lambda"
  description   = "Macie lambda function"
  handler       = "run.lambda_handler"
  runtime       = "python3.8"

  source_path = "${path.module}/../../backend/python/src/ccc_macie_lambda/lambda_handler.py"
  lambda_role = module.informational_macie_lambda_role.name
  environment_variables = {
    AWS_ENVIRONMENT                 = var.environment
  }
  tags = {
    name                = "nla-informational-macie-lambda-${var.environment}"
    tag-version         = ""
    billing-guid        = "Internal order - from SAP"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
    portfolio           = "Portfolio"
    unit                = "Unit"
  }
}

module "macie_lambda" {
  source  = "app.terraform.io/SempraUtilities/seu-lambda/aws"
  version = "6.0.0-prerelease"

  company_code     = "ent"
  application_code = "ccc"
  environment_code = "sbx"
  region_code      = "wus2"
  application_use  = "lambda"
  description   = "Macie lambda function"
  handler       = "run.lambda_handler"
  runtime       = "python3.8"

  source_path = "${path.module}/../../backend/python/src/ccc_macie_lambda/lambda_handler.py"
  lambda_role = module.macie_lambda_role.name
  environment_variables = {
    AWS_ENVIRONMENT                 = var.environment
  }
  tags = {
    name                = "ccc-macie-lambda-lambda-${var.environment}"
    tag-version         = ""
    billing-guid        = "Internal order - from SAP"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
    portfolio           = "Portfolio"
    unit                = "Unit"
  }
}
module "layers" {
  source                                = "./layers"
}
