locals {
  application_use  = "nla"
  region           = "us-west-2"
  namespace        = "internal.aws"
  company_code     = "sdge"
  application_code = "dwcko"
  environment_code = "sbx"
  region_code      = "wus2"
  owner            = "IAC Team"
  tags = {
    tag-version         = "Holds the version of the tagging format."
    billing-guid        = "Internal order - from SAP"
    unit                = "Organizational unit"
    portfolio           = "Portfolio associated with the application"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
  }
}

# Customercallcenterpiiunrefined 
# ccc-unrefined-call-data-bucket
module "ccc_unrefined_call_data_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags
  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_unrefined-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# customercallcenterpiitranscription
# ccc-initial-bucket
module "ccc_initial_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_initial-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# Customercallcenterpiicleaned
# ccc-clean-bucket
module "ccc_cleaned_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_clean-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# Customercallcenterpiicleanedverified
# ccc-verified-clean-bucket
module "ccc_verified_clean_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_verified_clean-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# customercallcenterpiidirty
# ccc-dirty-bucket
module "ccc_dirty_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_dirty-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# customercallcentermaciefindings
module "ccc_maciefindings_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_maciefindings-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# customercallcenterpiimetadata
module "ccc_piimetadata_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_piimetadata-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}

# customercallcenterathenaresults
module "ccc_athenaresults_bucket" {
  source  = "app.terraform.io/SempraUtilities/seu-s3/aws"
  version = "5.3.0"
  company_code      = local.company_code
  application_code  = local.application_code
  environment_code  = local.environment_code
  region_code       = local.region_code
  application_use   = "${local.application_use}-s3"
  owner                          = "IAC Team"
  create_bucket                  = true
  create_log_bucket              = false
  attach_alb_log_delivery_policy = false
  tags = local.tags

  acl = "private"
  server_side_encryption_configuration = { 
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = var.kms_key_ccc_athenaresults-arn
        sse_algorithm = "aws:kms"
      }
    }
  }
  cors_rule = [
    {
      allowed_methods = ["GET", "PUT", "POST"]
      allowed_origins = ["*"]
      allowed_headers = ["*"]
      expose_headers  = []
    }
  ]
}
