environment                 = "qa"
environment_code            = "qa"
tf_artifact_s3              = "sdge-dtdes-qa-wus2-s3-tf-artifacts"
aws_assume_role_pii         = "arn:aws:iam::596380883457:role/fondo/sdge-dtdes-qa-iam-role-ado-beta"
aws_assume_role_insights    = "arn:aws:iam::437147112758:role/fondo/sdge-dmeti-qa-iam-role-ado-beta"