variables:
  #Replace this with a different variable as needed. Kept here to avoid validation issues when no variables are needed for build stage.
  #Add variables here when they are unique per environment and referenced in Jobs added to the pipeline by the `LocalBuildYAML` pipeline parameter
  #More information, https://dev.azure.com/SempraUtilities/SempraUtilities/_wiki/wikis/SempraUtilities.wiki/3587/LocalBuildYAML
  - name: placeholder
  - group: sdge-it-nla-dev
