import os

UNREFINED = os.environ["UNREFINED_BUCKET_NAME"]
TRANSCRIPTION = os.environ["TRANSCRIPTION_BUCKET_NAME"]
CLEANED = os.environ["CLEANED_BUCKET_NAME"]
CLEANED_VERIFIED = os.environ["CLEANED_VERIFIED_BUCKET_NAME"]
DIRTY = os.environ["DIRTY_BUCKET_NAME"]
RECORDINGS = os.environ["CALL_RECORDINGS_BUCKET_NAME"]
METADATA = os.environ["METADATA_BUCKET_NAME"]
AUDIO = os.environ["AUDIO_BUCKET_NAME"]