# .github/workflows/deploy-to-env.yml
name: Deploy to Environment

on:
  push:
    branches:
      - master

#   workflow_dispatch:
#     inputs:
#       environment:
#         description: "Target Environment (dev, tst, qa, prd)"
#         required: true
#         type: choice
#         options:
#           - dev
#           - tst
#           - qa
#           - prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Environment
        #run: echo "Deploying to ${{ github.event.inputs.environment }}"
        run: echo "deploying to dev"

  call-lambda-deployment:
    needs: deploy  # Ensures Lambda deployment runs after the main deploy job
    uses: ./.github/workflows/lambda-deployment.yml  # Calls the reusable workflow
    with:
      #environment: ${{ github.event.inputs.environment }}
      environment: dev
