# .github/workflows/lambda-deployment.yml
name: Lambda Deployment

on:
  workflow_call:  # Enables this workflow to be called from another workflow
    inputs:
      environment:
        description: "Target Environment"
        required: true
        type: string

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AWS Lambda
        #run: echo "Deploying Lambda to ${{ inputs.environment }}"
        run: echo "Deploying Lambda to dev"
